from enum import Enum
class default_values(Enum):
    PERSONAL_DATA="No Hay Datos Personales Relevantes"
    FAMILY_DATA_FATHER="No hay precedentes importantes del lado paternal"
    FAMILY_DATA_MOTHER="No hay precedentes importantes del lado maternal"
    PHYS_EVAL="Parece estar en buen estado Fisico"

class symptoms(Enum):
    CEFALEA="Cefalea"
    CUTANEOUS_ERUPTIONS="Erupciones Cutaneas"
    STOMACHACHES="Dolores del Estomago"
    THIRST="Sensaciones de Mucha Sed"
    MORE_URINATION="Orinando con mas frecuencia"
    BLURRY_VISION="Vision Borrosa"
    TIREDNESS="Cansancio"
    INVOLUNTARY_WEIGHTLOSS="Perdida de Peso sin querer"
    HEADACHES="Dolores de Cabeza"
    CHESTPAINS="Dolores de Pecho"
    DIZZYNESS="Mareo"
    BREATHING_TROUBLES="Problemas para respirar"
    NAUSEA="Nausea"
    VOMITING="Vomitos"
    ANXIETY="Ansiedad"
    CONFUSION="Confusion"
    EAR_RINGING="Pitidos en los oidos"
    NASAL_HEMORRAGING="Hemorragia Nasal"
    IRREGULAR_HEARTBEAT="Ritmo Cardiaco Irregular"
    FEVER="Fiebre"
    EYE_PAIN="Dolor detras de los ojos"
    MUSCLE_PAIN="Dolor en Musculos y Articulaciones"
    RASH="Sarpullido"
    HEART_RHYTTHM_ALTERATION="Alteracion del Ritmo Cardiaco"
    ENLARGED_LYMPH_NODES="Agrandamiento de ganglios linfaticos"
    ACCELERATED_BREATHING="Resoiracion acelerada"
    BLOODY_STOOLS="Heces con sangre"
    SKIN_PALLOR="palidez cutanea"
    FRAILITY="debilidad"
    DIFFICULTY_TO_SLEEP="dificultad para dormir"
    SLEEP_APNEA="apnea del sueño"
    BACK_PAIN="dolor de espalda"
    INCREASED_SWEATING="aumento de la sudoracion"
    HEAT_INTOLERANCE="intolerancia al calor"
    SKIN_FOLD_INFECTIONS="infeccion de pliegues cutaneos"
    DEPRESSION="depresion"
    DYSPNOEA="disnea"
    FEELING_OF_LACK_OF_AIR="sensacion de falta de aire"
    